# This workflow will generate updated metadata when changes are merged into the master branch

name: Update json feed in GH Pages
on:
  push:
    branches:
      - master

jobs:
  update_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: generate-json
        run: |
          cd master
          python scripts/generate_store_data.py
      - name: copy updated json to frontend public
        run: |
          cd master
          mkdir -p frontend/public
          cp public/skills.json frontend/public/skills.json
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: ./master
          branch: master
          add: frontend/public/skills.json
          message: "Automated Metadata Update"
